/*
 * File: app/model/mail.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.mail', {
    extend: 'Ext.data.Model',
    alias: 'model.mailData',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'idMail',
            type: 'int'
        },
        {
            name: 'idCategory',
            type: 'int'
        },
        {
            name: 'read',
            type: 'boolean'
        },
        {
            name: 'priority',
            type: 'string'
        },
        {
            name: 'from',
            type: 'string'
        },
        {
            name: 'subject',
            type: 'string'
        },
        {
            name: 'date',
            type: 'date'
        },
        {
            name: 'content',
            type: 'string'
        },
        {
            name: 'attachment',
            type: 'string',
            useNull: true
        },
        {
            name: 'cc',
            type: 'string'
        },
        {
            name: 'cco',
            type: 'string'
        },
        {
            name: 'to',
            type: 'string'
        },
        {
            name: 'selected',
            type: 'boolean'
        }
    ]
});