/* auto generated by architect */ 
Ext.theme.addManifest([
    {
        "ui": "bluebutton",
        "xtype": "button"
    },
    {
        "ui": "headerpanelstyle",
        "xtype": "panel"
    },
    {
        "ui": "loginform",
        "xtype": "panel"
    }
]);