/*
 * File: app/view/AppView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AppView', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Label',
        'Ext.form.Panel',
        'Ext.Img',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Template',
        'Ext.XTemplate',
        'Ext.grid.View',
        'Ext.grid.column.CheckColumn',
        'Ext.grid.column.Date',
        'Ext.toolbar.Paging',
        'Ext.toolbar.Separator',
        'Ext.tree.Panel',
        'Ext.tree.View'
    ],

    id: 'appView',
    itemId: 'appView',
    layout: 'card',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    itemId: 'loginPanel',
                    width: 150,
                    header: false,
                    title: 'Login',
                    titleAlign: 'center',
                    items: [
                        {
                            xtype: 'label',
                            hidden: true,
                            html: '<div class="banner"> <h1>   Una cuenta. Todo Google. </h1>   <h2 class="hidden-small">   Inicia sesión para acceder a Gmail   </h2> </div>',
                            id: ''
                        },
                        {
                            xtype: 'form',
                            height: 350,
                            id: 'loginForm',
                            itemId: 'loginForm',
                            ui: 'loginform',
                            width: 360,
                            bodyPadding: 10,
                            header: false,
                            title: 'My Form',
                            items: [
                                {
                                    xtype: 'image',
                                    height: 96,
                                    id: 'profile-img',
                                    width: 96,
                                    src: 'resources/images/avatar.png'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    height: 44,
                                    id: 'txtUser',
                                    itemId: 'txtUser',
                                    maxWidth: 274,
                                    formItemCls: '',
                                    emptyText: '  Email',
                                    regexText: 'Enter your email.'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    height: 44,
                                    id: 'txtPassword',
                                    itemId: 'txtPassword',
                                    maxWidth: 274,
                                    inputType: 'password',
                                    emptyText: '  Password'
                                },
                                {
                                    xtype: 'button',
                                    height: 35,
                                    id: 'btnLogin',
                                    itemId: 'btnLogin',
                                    width: 274,
                                    text: 'Login'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    itemId: 'mainPanel',
                    ui: 'loginform',
                    layout: 'border',
                    header: false,
                    title: 'My Panel',
                    items: [
                        {
                            xtype: 'panel',
                            region: 'north',
                            height: 68,
                            itemId: 'headerPanel',
                            ui: 'headerpanelstyle',
                            layout: 'border',
                            title: 'Bienvenido, usuario',
                            titleAlign: 'right',
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 0.3,
                                    region: 'west',
                                    border: false,
                                    cls: 'centerAlign',
                                    id: 'titlePanel',
                                    width: 150,
                                    header: false,
                                    title: 'leftPanel',
                                    items: [
                                        {
                                            xtype: 'label',
                                            cls: 'mainTitle',
                                            text: 'VMail'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1.5,
                                    region: 'center',
                                    border: false,
                                    cls: 'textLeftAligned',
                                    header: false,
                                    title: 'centerPanel',
                                    titleAlign: 'center',
                                    items: [
                                        {
                                            xtype: 'button',
                                            border: ' ',
                                            cls: 'btnGray',
                                            itemId: 'btnRefresh',
                                            margin: '6 2 6 2',
                                            padding: '6px 18px 6px 25px',
                                            icon: 'resources/images/reload.png',
                                            text: ' '
                                        },
                                        {
                                            xtype: 'button',
                                            border: ' ',
                                            cls: 'btnGray',
                                            itemId: 'newMailButton',
                                            margin: '6 2 6 2',
                                            padding: '6px 18px 6px 25px',
                                            icon: 'resources/images/mail.png',
                                            text: ' '
                                        },
                                        {
                                            xtype: 'button',
                                            border: '',
                                            cls: 'btnGray',
                                            id: 'deleteButton',
                                            itemId: 'btnDeleteSelected',
                                            margin: '6 2 6 2',
                                            padding: '6px 18px 6px 25px',
                                            icon: 'resources/images/trash.png',
                                            text: ' '
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 0.3,
                                    region: 'east',
                                    border: false,
                                    cls: 'textRightAligned',
                                    width: 210,
                                    header: false,
                                    title: 'rightPanel',
                                    items: [
                                        {
                                            xtype: 'button',
                                            border: ' ',
                                            cls: 'btnGray',
                                            id: 'btnLogout',
                                            itemId: 'btnLogout',
                                            margin: '6 2 6 2',
                                            padding: '6px 18px 6px 25px',
                                            icon: 'resources/images/lock.png',
                                            text: ' '
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 0.3,
                            region: 'east',
                            split: true,
                            itemId: 'leftPanel',
                            width: 150,
                            autoScroll: true,
                            layout: 'fit',
                            bodyPadding: '',
                            collapsible: false,
                            header: false,
                            title: 'Contacts',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    itemId: 'contactGrid',
                                    margin: '',
                                    header: false,
                                    manageHeight: false,
                                    title: 'My Grid Panel',
                                    emptyText: 'Add some contacts',
                                    hideHeaders: true,
                                    store: 'ContactStore',
                                    columns: [
                                        {
                                            xtype: 'templatecolumn',
                                            tpl: [
                                                '<table>',
                                                '    <tr>',
                                                '        <td style="padding-right: 8px; vertical-align:middle;">',
                                                '            <img src="resources/images/status/{status}.png" title="{status} Priority" style="margin-bottom: -2px;" />&nbsp;{name}&nbsp;{lastname}',
                                                '        </td>',
                                                '    </tr>',
                                                '</table>'
                                            ],
                                            dataIndex: 'status',
                                            text: 'MyTemplateColumn1',
                                            flex: 1
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1.5,
                            region: 'center',
                            split: true,
                            draggable: true,
                            itemId: 'centerPanel',
                            minWidth: 200,
                            layout: 'border',
                            collapsible: false,
                            header: false,
                            title: 'Mail',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    region: 'west',
                                    split: true,
                                    border: '2 2 2 2',
                                    id: 'gridMailPanel',
                                    itemId: 'gridPanel',
                                    width: 150,
                                    collapsed: false,
                                    collapsible: false,
                                    header: false,
                                    manageHeight: false,
                                    title: 'Inbox',
                                    forceFit: true,
                                    hideHeaders: true,
                                    store: 'MailStore',
                                    columns: [
                                        {
                                            xtype: 'checkcolumn',
                                            itemId: 'checkMail',
                                            width: 30,
                                            dataIndex: 'selected',
                                            hideable: false,
                                            text: 'MyCheckColumn',
                                            stopSelection: false
                                        },
                                        {
                                            xtype: 'templatecolumn',
                                            tpl: [
                                                '<table>',
                                                '    <tr>',
                                                '        <td style="padding-right: 8px; vertical-align:middle;">',
                                                '            <img src="resources/images/{priority}.png" title="{priority} Priority" />',
                                                '        </td>',
                                                '    </tr>',
                                                '</table>'
                                            ],
                                            width: 35,
                                            dataIndex: 'priority',
                                            text: 'MyTemplateColumn'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'from',
                                            text: 'MyColumn4'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'subject',
                                            text: 'MyColumn5'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            defaultWidth: 200,
                                            dataIndex: 'date',
                                            text: 'MyDateColumn2'
                                        }
                                    ],
                                    viewConfig: {
                                        height: 500,
                                        emptyText: 'There are no mails in your inbox'
                                    }
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    region: 'center',
                                    split: true,
                                    border: '2 2 2 2',
                                    itemId: 'mailPanel',
                                    tpl: [
                                        '<tpl if="values.idMail">',
                                        '    <h1>{subject}</h1>',
                                        '    <p>',
                                        '        {content}',
                                        '    </p>',
                                        '</tpl>',
                                        '',
                                        '<tpl if="!values.idMail">',
                                        '',
                                        '</tpl>'
                                    ],
                                    autoScroll: true,
                                    layout: 'fit',
                                    bodyPadding: '10 10 10 10',
                                    collapsible: false,
                                    header: false,
                                    manageHeight: false,
                                    title: 'My Panel',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            hidden: true,
                                            itemId: 'mailToolbar',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnReplay',
                                                    icon: 'resources/images/reply.png',
                                                    text: ''
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnForward',
                                                    icon: 'resources/images/forward.png',
                                                    text: ''
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnDelete',
                                                    icon: 'resources/images/trash.png',
                                                    text: ''
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    id: 'paginator',
                                    itemId: 'pagingToolbar',
                                    displayInfo: true,
                                    emptyMsg: 'No mails to display',
                                    store: 'MailStore'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 0.3,
                            region: 'west',
                            split: true,
                            cls: '',
                            itemId: 'rightPanel',
                            width: 150,
                            bodyPadding: 10,
                            collapsible: true,
                            header: false,
                            title: '',
                            items: [
                                {
                                    xtype: 'treepanel',
                                    itemId: 'categoryTreePanel',
                                    autoScroll: true,
                                    collapsible: false,
                                    title: '',
                                    store: 'CategoryStore',
                                    folderSort: true,
                                    rootVisible: false,
                                    viewConfig: {
                                        itemId: 'categoryTree'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});