/*
 * File: app/view/mailPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.mailPanel', {
    extend: 'Ext.window.Window',
    alias: 'widget.newMailPanel',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.File',
        'Ext.form.field.HtmlEditor',
        'Ext.button.Button'
    ],

    itemId: 'newMailForm',
    width: 650,
    title: 'New Mail',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'mailForm',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            hidden: true,
                            itemId: 'contactList',
                            fieldLabel: 'Label',
                            anyMatch: true,
                            displayField: 'name',
                            minChars: 1,
                            multiSelect: true,
                            queryMode: 'local',
                            store: 'ContactStore'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'txtTo',
                            fieldLabel: 'To:',
                            name: 'to'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'txtFrom',
                            fieldLabel: 'From:',
                            name: 'from',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'txtCc',
                            fieldLabel: 'Cc:',
                            name: 'cc'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'txtCco',
                            fieldLabel: 'Cco:',
                            name: 'cco'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'txtSubject',
                            fieldLabel: 'Subject:',
                            name: 'subject'
                        },
                        {
                            xtype: 'filefield',
                            anchor: '100%',
                            itemId: 'txtUpload',
                            rtl: true,
                            fieldLabel: '',
                            name: 'upload'
                        },
                        {
                            xtype: 'htmleditor',
                            anchor: '100%',
                            height: 255,
                            itemId: 'txtMailContent',
                            name: 'content'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSend',
                            ui: 'bluebutton',
                            scale: 'medium',
                            text: 'Send'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});